// WOS 편성 계산기 — 영웅 데이터베이스
// 출처: wosheroes.com / whiteoutsurvival-community.com / whiteoutsurvival.wiki (2026-08-15 수집)
// pc:<확률> — 그 확률이 **병종마다 독립으로** 굴러가는 스킬. v 는 1병종 기준값이고,
//   엔진이 편성 병종 수 n 으로 (1−(1−pc)^n)/pc 를 곱해 기대값을 다시 낸다.
//   근거: 원문 "Grants all troops' attack a 50% chance of cursing the target" +
//   볼트 「랠리 조이너 선정 규칙·개리슨 운영 (Ton)」 §6 — 3병종이면 87.5% 발동, 기대값 43.75%.
// bk:"A"|"D" — slot:"X" 전용. 병종 한정이지만 원문이 "Damage Dealt / Damage Taken" 스탯을
//   올리는(내리는) 스킬이라는 표시다. 이런 스킬은 일반 칸과 같은 스탯이므로 칸을 우회하면 안 되고,
//   병종 딜 지분(dmg) 또는 병력 지분(sur)으로 환산해 그 칸에 합산한다. 근거는 wosheroes 원문이고,
//   "extra damage / 추가피해" 처럼 타격에 붙는 것은 다른 기전이라 bk 를 달지 않는다.
// stack:1 — 시트가 **한 행에 같은 칸을 두 번 이상 적은** 영웅. 지금 둘이다 — 노라(11행) · 패트릭(2행).
//   ⚠️ 이 목록을 기억으로 적지 말 것. `SHEET_COMPS` 에서 기계적으로 세서 맞춰야 한다 —
//   실제로 2026-09-13 까지 "노라 하나뿐"이라고 적어 두었는데 Gen 1 두 행의 패트릭을 놓치고 있었다.
//   `unit.mjs` 가 **stack 이 붙은 영웅 집합 == 시트가 겹쳐 쓴 영웅 집합** 을 검사한다.
//   근거 — 노라: 볼트 「랠리 참여자 영웅 가이드」 257행 "스택 시에도 효율이 좋은 특수 케이스".
//   패트릭: Gen 1 은 풀이 얇아서 **2장째 패트릭(×1.185)이 20% 계열(세르게이·바히티 ×1.167)보다 낫다.**
//   우리 순위표에서도 그렇게 나온다(사용자가 짚어준 이유이고, 숫자로 확인됐다).
//   ⚠️ 단 **고를 수 있게만** 해 주는 플래그지 "쌀라"는 지시가 아니다. 둘째 장은 같은 칸에
//   합연산으로 들어가 자기끼리 포화한다 — 순수 계산은 더 나을 때만 집는다.
// slot:"AH" — 위 규칙의 짝이다. 원문이 "extra damage / extra attack / N% damage" 처럼
//   **타격에 붙는** 것은 Damage Dealt 스탯이 아니므로 A칸(합연산)에 넣지 않는다.
//   어느 칸인지는 자료가 없으니 칸을 만들지도 않는다 — 자기 계수로만 곱한다(포화 없음).
//   X 스킬에서 extra damage 계열에 bk 를 달지 않는 것과 **같은 규칙**이고, 예전에는
//   이 둘이 어긋나 있었다(X 는 칸을 피하는데 일반 칸은 A 에 합산). 2026-09-12 정정.
// slot 코드: A=피해량↑ AH=타격 추가피해(칸 아님) An=일반공격피해↑ B=공격력↑ C=체력↑ D=받는피해↓ DEF=방어력↑
//            E=파괴력↑ F=적방어↓ G=적받는피해↑ H=적공격↓ I=적파괴력↓ J=적피해량↓
//            DODGE=회피 CRIT=치명률 X=병종한정/주기형 ECO=비전투
// s:1 = Ton 시트의 **조이너 명단**에 오른 영웅 (19명). 리더로만 나오는 영웅은 붙이지 않는다 —
//       이 플래그를 쓰는 곳이 ⑤ 의 "시트 등재 영웅만" 조이너 추천 하나뿐이기 때문이다.
//       2026-09-01 갱신(시트 Gen 10+ 탭 신설): 범례의 "Sergey = Bahiti, Lumak Bokan" 과
//       Gen 1 행 대체 조이너 Ling Xue 를 반영해 룸 보겐·료우키를 넣고,
//       시트에 리더로만 나오는 몰리·알론소·그렉을 뺐다. 조이너 명단 자체는 Gen 8 이하 그대로다.
const HEROES = [
// ── Epic (원정스킬 2개, 전용무기 없음) ──
{id:"jessie",s:1,kr:"제시",en:"Jessie",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Stand of Arms",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"},
      {n:"Bulwarks",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"}],w:null},
{id:"jasser",s:1,kr:"제셀",en:"Jasser",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Tactical Genius",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"},
      {n:"Enlightened Warfare",slot:"ECO",v:0,t:"연구 속도 +15%",te:"research speed +15%"}],w:null},
{id:"seoyoon",s:1,kr:"서윤",en:"Seo-yoon",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Rallying Beat",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Soothing Dance",slot:"ECO",v:0,t:"의무실 치료 속도 +50%",te:"infirmary healing speed +50%"}],w:null},
{id:"patrick",s:1,stack:1,kr:"패트릭",en:"Patrick",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Super Nutrients",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"},
      {n:"Caloric Booster",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"}],w:null},
{id:"sergey",s:1,kr:"세르게이",en:"Sergey",cls:"infantry",gen:0,rar:"epic",
 exp:[{n:"Defenders' Edge",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Weaken",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"}],w:null},
{id:"bahiti",s:1,kr:"바히티",en:"Bahiti",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Sixth Sense",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Fluorescence",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 피해량 +50%",te:"50% chance: damage +50%"}],w:null},
{id:"lumak",s:1,kr:"룸 보겐",en:"Lumak Bokan",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Tactical Deception",slot:"J",v:.20,t:"적 전 부대 피해량 −20%",te:"all enemy troops damage −20%"},
      {n:"Emerald Warrior",slot:"ECO",v:0,t:"사냥 행군 속도 +100%",te:"hunting march speed +100%"}],w:null},
{id:"gina",kr:"지나",en:"Gina",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Endurance Training",slot:"ECO",v:0,t:"체력 소모 −20%",te:"stamina cost −20%"},
      {n:"Quick Paced",slot:"ECO",v:0,t:"사냥 행군 속도 +100%",te:"hunting march speed +100%"}],w:null},
{id:"lingxue",s:1,kr:"료우키",en:"Ling Xue",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Fearsome Aura",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Total Control",slot:"ECO",v:0,t:"훈련 속도 +20%",te:"training speed +20%"}],w:null},
// ── Gen 1 ──
{id:"jeronimo",s:1,kr:"제로니모",en:"Jeronimo",cls:"infantry",gen:1,rar:"leg",
 exp:[{n:"Battle Manifesto",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"},
      {n:"Swordmentor",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Expert Swordsmanship",slot:"A",v:.15,p:"4턴중 2턴",pe:"2 turns out of 4",t:"4턴마다 2턴 피해량 +30% (시간평균 15%)",te:"2 turns out of every 4: damage +30% (time-averaged 15%)"}],
 w:{side:"rally",stat:"Attack",name:"Discernment"}},
{id:"natalia",kr:"나탈리아",en:"Natalia",cls:"infantry",gen:1,rar:"leg",
 exp:[{n:"Feral Protection",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"},
      {n:"Queen of the Wild",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Call of the Wild",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"}],
 w:{side:"rally",stat:"Lethality",name:"Invincibles"}},
{id:"molly",kr:"몰리",en:"Molly",cls:"lancer",gen:1,rar:"leg",
 exp:[{n:"Snow's Grace",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"},
      {n:"Ice Dominion",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 피해량 +50%",te:"50% chance: damage +50%"},
      {n:"Youthful Rage",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"}],
 w:{side:"defender",stat:"Lethality",name:"Snowy Blessing"}},
{id:"zinman",s:1,kr:"진먼",en:"Zinman",cls:"marksman",gen:1,rar:"leg",
 exp:[{n:"Implacable",slot:"DEF",v:.10,t:"방어력 +10% / 체력 +10%",te:"defense +10% / health +10%",also:{slot:"C",v:.10}},
      {n:"Bastionist",slot:"ECO",v:0,t:"자원 소모 −15% / 건설 속도 +15%",te:"resource cost −15% / construction speed +15%"},
      {n:"Positional Battler",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"}],
 w:{side:"defender",stat:"Attack",name:"Defend to Attack"}},
// ── Gen 2 ──
{id:"flint",kr:"플린트",en:"Flint",cls:"infantry",gen:2,rar:"leg",
 exp:[{n:"Pyromaniac",slot:"X",k:"dmg",v:1.0,tgt:"infantry",bk:"A",t:"보병 피해량 +100%",te:"infantry damage +100%"},
      {n:"Burning Resolve",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Immolation",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"}],
 w:{side:"defender",stat:"Attack",name:"Dragonbreath"}},
{id:"philly",s:1,kr:"필리",en:"Philly",cls:"lancer",gen:2,rar:"leg",
 exp:[{n:"Vigor Tactics",slot:"B",v:.15,t:"공격력 +15% / 방어력 +10%",te:"attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Dosage Boost",slot:"AH",v:.50,p:"25%",pe:"25% chance",t:"25% 확률 200% 피해",te:"25% chance: 200% damage"},
      {n:"Energizing Shot",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"}],
 w:{side:"defender",stat:"Health",name:"First Aid Training"}},
{id:"alonso",kr:"알론소",en:"Alonso",cls:"marksman",gen:2,rar:"leg",
 exp:[{n:"Onslaught",slot:"E",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 파괴력 +50%",te:"40% chance: lethality +50%"},
      {n:"Iron Strength",slot:"J",v:.10,p:"20%",pe:"20% chance",t:"20% 확률 적 피해량 −50%",te:"20% chance: enemy damage −50%"},
      {n:"Poison Harpoon",slot:"AH",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 추가피해 +50%",te:"50% chance: +50% extra damage"}],
 w:{side:"rally",stat:"Lethality",name:"Harpoon Enhancement"}},
// ── Gen 3 ──
{id:"logan",kr:"로건",en:"Logan",cls:"infantry",gen:3,rar:"leg",
 exp:[{n:"Lion's Might",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Lion Intimidation",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Leader Inspiration",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"}],
 w:{side:"defender",stat:"Defense",name:"Strong Protection"}},
{id:"mia",s:1,kr:"미야",en:"Mia",cls:"lancer",gen:3,rar:"leg",
 exp:[{n:"Bad Luck Streak",slot:"G",v:.25,p:"50%",pe:"50% chance",pc:.5,t:"병종마다 50% 확률 적 받는 피해 +50%",te:"each troop type: 50% chance, enemy damage taken +50%"},
      {n:"Lucky Charm",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 피해량 +50%",te:"50% chance: damage +50%"},
      {n:"Ritual Deciphering",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"}],
 w:{side:"rally",stat:"Attack",name:"Rally of Fate"}},
{id:"greg",kr:"그렉",en:"Greg",cls:"marksman",gen:3,rar:"leg",
 exp:[{n:"Sword of Justice",slot:"A",v:.08,p:"20%",pe:"20% chance",t:"20% 확률 피해량 +40%(3턴)",te:"20% chance: damage +40% (3 turns)"},
      {n:"Deterrence of Law",slot:"J",v:.10,p:"20%",pe:"20% chance",t:"20% 확률 적 피해량 −50%",te:"20% chance: enemy damage −50%"},
      {n:"Law and Order",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"}],
 w:{side:"rally",stat:"Health",name:"Trumpet of Justice"}},
// ── Gen 4 ──
{id:"ahmose",kr:"아모세",en:"Ahmose",cls:"infantry",gen:4,rar:"leg",
 exp:[{n:"Viper Formation",slot:"X",k:"sur",v:.35,tgt:"infantry",t:"4공격마다 2턴 보병 받피 −70%, 창·궁 −30%",te:"every 4th attack, 2 turns: infantry damage taken −70%, lancer/marksman −30%"},
      {n:"Prayer of Flame",slot:"X",k:"dmg",v:1.0,tgt:"infantry",bk:"A",t:"보병 피해량 +100%",te:"infantry damage +100%"},
      {n:"Blade of Light",slot:"X",k:"dmg",v:.60,tgt:"infantry",t:"보병 공격당 피해 +60% & 대상 받피 +25%",te:"infantry, per attack: +60% damage & target takes +25% damage"}],
 w:{side:"defender",stat:"Health",name:"Oath of Guardian"}},
{id:"reina",s:1,kr:"레이나",en:"Reina",cls:"lancer",gen:4,rar:"leg",
 exp:[{n:"Assassin's Instinct",slot:"An",v:.30,t:"일반공격 피해 +30%",te:"normal-attack damage +30%"},
      {n:"Swift Jive",slot:"DODGE",v:.20,t:"일반공격 20% 회피",te:"20% chance to dodge normal attacks"},
      {n:"Shadow Blade",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 25% 확률 200% 추가공격",te:"lancers, 25% chance: a 200% extra attack"}],
 w:{side:"rally",stat:"Lethality",name:"Fiery Invasion"}},
{id:"lynn",s:1,kr:"린",en:"Lynn",cls:"marksman",gen:4,rar:"leg",
 exp:[{n:"Song of Lion",slot:"A",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 피해량 +50%",te:"40% chance: damage +50%"},
      {n:"Melancholic Ballad",slot:"J",v:.20,t:"적 전 부대 피해량 −20%",te:"all enemy troops damage −20%"},
      {n:"Oonai Cadenza",slot:"X",k:"dmg",v:.05,tgt:"marksman",t:"궁병 3공격마다 공격력 +5% 누적",te:"marksmen, every 3rd attack: attack +5%, stacking"}],
 w:{side:"defender",stat:"Lethality",name:"Iranon's Determination"}},
// ── Gen 5 ──
{id:"hector",kr:"헥터",en:"Hector",cls:"infantry",gen:5,rar:"leg",
 exp:[{n:"Survival Instincts",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"},
      {n:"Rampant",slot:"X",k:"dmg",v:1.07,tgt:"infantry",bk:"A",also:{slot:"X",k:"dmg",v:.535,tgt:"marksman",bk:"A"},t:"보병 피해량 +200% · 궁병 +100% (10회 동안 매 공격 85%로 감쇠 → 평균 0.535 환산)",te:"infantry damage +200%, marksmen +100% (decays over 10 procs)"},
      {n:"Blitz",slot:"AH",v:.50,p:"25%",pe:"25% chance",t:"25% 확률 200% 피해",te:"25% chance: 200% damage"}],
 w:{side:"defender",stat:"Attack",name:"Goliath"}},
{id:"norah",s:1,stack:1,kr:"노라",en:"Norah",cls:"lancer",gen:5,rar:"leg",
 exp:[{n:"Combined Arms",slot:"X",k:"dmg",v:.15,tgt:"inf+mar",bk:"A",also:{slot:"X",k:"sur",v:.15,tgt:"inf+mar",bk:"D"},t:"보병·궁병 받피 −15% & 피해량 +15%",te:"infantry & marksmen: damage taken −15% and damage +15%"},
      {n:"Sneak Strike",slot:"X",k:"dmg",v:.20,tgt:"lancer",t:"창병 20% 확률 추가피해 +100%",te:"lancers, 20% chance: +100% extra damage"},
      {n:"Momentum",slot:"A",v:.25,p:"창병 5공격마다",pe:"lancers, every 5th attack",t:"피해량 +25% & 받피 −25% (2턴)",te:"damage +25% & damage taken −25% (2 turns)",also:{slot:"D",v:.25}}],
 w:{side:"defender",stat:"Defense",name:"True Grit"}},
{id:"gwen",kr:"그웬",en:"Gwen",cls:"marksman",gen:5,rar:"leg",
 exp:[{n:"Eagle Vision",slot:"G",v:.25,t:"적 받는 피해 +25%",te:"enemy damage taken +25%"},
      {n:"Air Dominance",slot:"AH",v:.20,p:"5공격마다",pe:"every 5th attack",t:"5공격마다 추가피해 +100%",te:"every 5th attack: +100% extra damage"},
      {n:"Blastmaster",slot:"X",k:"dmg",v:.125,tgt:"marksman",t:"궁병 4공격마다 추가피해 +50%",te:"marksmen, every 4th attack: +50% extra damage"}],
 w:{side:"rally",stat:"Lethality",name:"Marauder"}},
// ── Gen 6 ──
{id:"wuming",s:1,kr:"무명",en:"Wu Ming",cls:"infantry",gen:6,rar:"leg",
 exp:[{n:"Shadow's Evasion",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 일반공격 받피 −25% / 스킬 받피 −30%",te:"infantry: normal-attack damage taken −25% / skill damage taken −30%"},
      {n:"Crescent Uplift",slot:"A",v:.20,t:"전 부대 피해량 +20%",te:"all troops damage +20%"},
      {n:"Elemental Resonance",slot:"A",v:.25,t:"전 부대 스킬 피해 +25%",te:"all troops skill damage +25%"}],
 w:{side:"defender",stat:"Defense",name:"Steel Discipline"}},
// ⚠️ Nightmare Trace 의 bk:"A" 는 **원문 문구 규칙의 유일한 예외**다(2026-09-13).
// 원문이 "extra damage" 라 규칙대로면 칸이 아닌데, 시트를 정답지로 놓고 스킬 타입을
// 전수로 쓸어 보니 이 한 건만 두 지표가 같은 방향으로 움직였다 — 자세한 근거는
// test/fixtures.mjs 의 X_BUCKETED 주석과 CLAUDE.md 정정 이력에 있다.
{id:"renee",s:1,kr:"레니",en:"Renee",cls:"lancer",gen:6,rar:"leg",
 exp:[{n:"Nightmare Trace",slot:"X",k:"dmg",bk:"A",v:1.0,tgt:"lancer",t:"창병 2턴마다 추가딜 200%",te:"lancers, every 2 turns: +200% extra damage"},
      {n:"Dreamcatcher",slot:"X",k:"dmg",v:1.5,tgt:"lancer",t:"표식 대상 창병 피해량 +150%",te:"vs marked targets: lancer damage +150%"},
      {n:"Dreamslice",slot:"A",v:.35,t:"표식 대상 전 부대 피해량 +75%",te:"vs marked targets: all troops damage +75%"}],
 w:{side:"rally",stat:"Lethality",name:"Wistful Enchantment"}},
{id:"wayne",kr:"웨인",en:"Wayne",cls:"marksman",gen:6,rar:"leg",
 exp:[{n:"Thunder Strike",slot:"AH",v:.25,p:"4턴마다",pe:"every 4 turns",t:"4턴마다 전 부대 추가공격 100%",te:"every 4 turns: all troops deal a 100% extra attack"},
      {n:"Roundabout Hit",slot:"X",k:"dmg",v:.40,tgt:"marksman",t:"궁병 격턴 적 창병 +40%/궁병 +20% 추가피해",te:"marksmen, every other turn: +40% extra vs enemy lancers, +20% vs marksmen"},
      {n:"Fleet",slot:"CRIT",v:.25,t:"전 부대 치명률 +25%",te:"all troops crit rate +25%"}],
 w:{side:"defender",stat:"Lethality",name:"Offensive Defense"}},
// ── Gen 7 ──
{id:"edith",kr:"에디스",en:"Edith",cls:"infantry",gen:7,rar:"leg",
 exp:[{n:"Strategic Balance",slot:"X",k:"sur",v:.20,tgt:"mar+lan",t:"궁병 받피 −20% / 창병 피해량 +20%",te:"marksman damage taken −20% / lancer damage +20%"},
      {n:"Ironclad",slot:"X",k:"sur",v:.20,tgt:"infantry",t:"보병 받는 피해 −20%",te:"infantry damage taken −20%"},
      {n:"Steel Sentinel",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"}],
 w:{side:"defender",stat:"Health",name:"Fortworks"}},
{id:"gordon",kr:"고든",en:"Gordon",cls:"lancer",gen:7,rar:"leg",
 exp:[{n:"Venom Infusion",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 2공격마다 추가딜 100% + 독(적 딜 −20%)",te:"lancers, every 2nd attack: +100% extra damage + poison (enemy damage −20%)"},
      {n:"Chemical Terror",slot:"X",k:"dmg",v:.50,tgt:"lancer",bk:"A",t:"창병 피해량 +150% & 적 피해량 −30% (3턴마다)",te:"lancer damage +150% & enemy damage −30% (every 3 turns)"},
      {n:"Toxic Release",slot:"G",v:.30,p:"4턴마다 2턴",pe:"2 turns out of every 4",t:"적 보병 받피 +30% & 적 궁병 피해량 −30%",te:"enemy infantry damage taken +30% & enemy marksman damage −30%"}],
 w:{side:"rally",stat:"Lethality",name:"Bio Assault"}},
{id:"bradley",kr:"브레들리",en:"Bradley",cls:"marksman",gen:7,rar:"leg",
 exp:[{n:"Veteran's Might",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Power Shot",slot:"AH",v:.25,t:"적 창병에 +30% / 적 보병에 +25% 피해",te:"+30% damage vs enemy lancers / +25% vs enemy infantry"},
      {n:"Tactical Assistance",slot:"A",v:.15,p:"4턴중 2턴",pe:"2 turns out of 4",t:"4턴마다 2턴 피해량 +30%",te:"2 turns out of every 4: damage +30%"}],
 w:{side:"defender",stat:"Attack",name:"Siege Insight"}},
// ── Gen 8 ──
{id:"gatot",s:1,kr:"가토",en:"Gatot",cls:"infantry",gen:8,rar:"leg",
 exp:[{n:"Golden Guard",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 방어력 +30%",te:"infantry defense +30%"},
      {n:"King's Bestowal",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 공격 시 보호막(공격력 30%)",te:"infantry attacks grant a shield (30% of attack)"},
      {n:"Royal Legion",slot:"H",v:.25,t:"적 전 부대 공격력 −25%",te:"all enemy troops attack −25%"}],
 w:{side:"defender",stat:"Defense",name:"Indestructible City"}},
{id:"sonya",kr:"소냐",en:"Sonya",cls:"lancer",gen:8,rar:"leg",
 exp:[{n:"Treasure Hunter",slot:"A",v:.20,t:"전 부대 피해량 +20%",te:"all troops damage +20%"},
      {n:"Bounty Temptation",slot:"B",v:.25,p:"2공격마다",pe:"every 2nd attack",t:"창병 피해 +75% & 전 부대 공격력 +25%(1턴)",te:"lancer damage +75% & all troops attack +25% (1 turn)"},
      {n:"Torrential Impact",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 5턴마다 250% 피해 + 기절",te:"lancers, every 5 turns: 250% damage + stun"}],
 w:{side:"defender",stat:"Lethality",name:"Vortex Turret"}},
{id:"hendrik",s:1,kr:"헨드릭",en:"Hendrik",cls:"marksman",gen:8,rar:"leg",
 exp:[{n:"Worm's Ravage",slot:"F",v:.25,t:"적 전 부대 방어력 −25%",te:"all enemy troops defense −25%"},
      {n:"Armor of Barnacles",slot:"DEF",v:.15,p:"4턴중 2턴",pe:"2 turns out of 4",t:"4턴마다 2턴 방어력 +30%",te:"2 turns out of every 4: defense +30%"},
      {n:"Dagon's Heir",slot:"X",k:"dmg",v:.133,tgt:"marksman",t:"궁병과 3턴마다 합공 40%",te:"joint strike with marksmen every 3 turns, 40%"}],
 w:{side:"rally",stat:"Attack",name:"Abyssal Blessing"}},
// ── Gen 9 ──
{id:"magnus",kr:"마그누스",en:"Magnus",cls:"infantry",gen:9,rar:"leg",
 exp:[{n:"Rapacious",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Iron Phalanx",slot:"X",k:"sur",v:.20,tgt:"infantry",p:"40%",pe:"40% chance",t:"보병 40% 확률 방어력 +50%",te:"infantry, 40% chance: defense +50%"},
      {n:"Iceman",slot:"X",k:"sur",v:.10,tgt:"inf+mar",t:"보병 받피 −10% / 궁병 피해 +10%",te:"infantry damage taken −10% / marksman damage +10%"}],
 w:{side:"defender",stat:"Health",name:"Valoric Inspiration"}},
{id:"fred",kr:"프레드",en:"Fred",cls:"lancer",gen:9,rar:"leg",
 exp:[{n:"Hydraulic Suppression",slot:"I",v:.20,t:"적 전 부대 파괴력 −20%",te:"all enemy troops lethality −20%"},
      {n:"Acidification",slot:"G",v:.20,t:"적 보병 받는 피해 +20%",te:"enemy infantry damage taken +20%"},
      {n:"Floodbringer",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 4격마다 추가피해 +200% & 적 딜 −20%",te:"lancers, every 4th hit: +200% extra damage & enemy damage −20%"}],
 w:{side:"rally",stat:"Attack",name:"Call of the Firefighter"}},
{id:"xura",kr:"쇠라",en:"Xura",cls:"marksman",gen:9,rar:"leg",
 exp:[{n:"Fungal Fog",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Piercing Arrow",slot:"X",k:"dmg",v:.50,tgt:"marksman",t:"궁병 2격마다 추가피해 +100% & 대상 받피 +25%",te:"marksmen, every 2nd hit: +100% extra damage & target takes +25% damage"},
      {n:"Unorthodoxy",slot:"X",k:"dmg",v:.10,tgt:"marksman",bk:"A",also:{slot:"X",k:"sur",v:.15,tgt:"marksman",bk:"D"},t:"궁병 피해량 +10% / 받피 −15%",te:"marksman damage +10% / damage taken −15%"}],
 w:{side:"defender",stat:"Attack",name:"Gaiac Hymn"}},
// ── Gen 10 ──
{id:"gregory",kr:"그레고리",en:"Gregory",cls:"infantry",gen:10,rar:"leg",
 exp:[{n:"Legion of the Sun",slot:"B",v:.15,t:"공격력 +15% / 방어력 +10%",te:"attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Charged Assault",slot:"CRIT",v:.25,t:"전 부대 치명 확률 +25%",te:"all troops crit chance +25%"},
      {n:"Unbroken",slot:"X",k:"sur",v:.20,tgt:"infantry",t:"보병 받는 피해 −20%",te:"infantry damage taken −20%"}],
 w:{side:"defender",stat:"Lethality",name:"Day of the Guard"}},
{id:"freya",kr:"프레야",en:"Freya",cls:"lancer",gen:10,rar:"leg",
 exp:[{n:"Fog of War",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Blood Moon Scythe",slot:"X",k:"dmg",v:.50,tgt:"lancer",p:"50%",pe:"50% chance",t:"창병 50% 확률 100% 추가피해",te:"lancers, 50% chance: +100% extra damage"},
      {n:"Night's Vengeance",slot:"X",k:"dmg",v:.15,tgt:"inf+mar",bk:"A",also:{slot:"X",k:"sur",v:.15,tgt:"inf+mar",bk:"D"},t:"보병·궁병 받피 −15% & 피해량 +15%",te:"infantry & marksmen: damage taken −15% and damage +15%"}],
 w:{side:"defender",stat:"Defense",name:"Defender of the Watch"}},
{id:"blanchette",kr:"블랑쉬",en:"Blanchette",cls:"marksman",gen:10,rar:"leg",
 exp:[{n:"Armed to the Teeth",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"},
      {n:"Blood Hunter",slot:"X",k:"dmg",v:.25,tgt:"marksman",t:"궁병 3라운드마다 추가피해 +75%",te:"marksmen, every 3rd round: +75% extra damage"},
      {n:"Crimson Sniper",slot:"X",k:"dmg",v:.20,tgt:"marksman",t:"궁병 2격마다 적 창병 +40%/궁병 +20%",te:"marksmen, every 2nd hit: +40% vs enemy lancers, +20% vs marksmen"}],
 w:{side:"rally",stat:"Lethality",name:"Lightning Strike"}},
// ── Gen 11 ──
{id:"eleonora",kr:"엘레오노라",en:"Eleonora",cls:"infantry",gen:11,rar:"leg",
 exp:[{n:"Scorching Sun",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"},
      {n:"Solaris Nexus",slot:"X",k:"sur",v:.10,tgt:"inf+mar",t:"보병 받피 −10% / 궁병 피해량 +10%",te:"infantry damage taken −10% / marksman damage +10%"},
      {n:"Soaring Flame",slot:"A",v:.25,p:"보병 5공격마다",pe:"infantry, every 5th attack",t:"피해량 +25% & 받피 −25% (2턴)",te:"damage +25% & damage taken −25% (2 turns)",also:{slot:"D",v:.25}}],
 w:{side:"defender",stat:"Health",name:"Last Fortress"}},
{id:"lloyd",kr:"로이드",en:"Lloyd",cls:"lancer",gen:11,rar:"leg",
 exp:[{n:"Bird Invasion",slot:"I",v:.20,t:"적 전 부대 파괴력 −20%",te:"all enemy troops lethality −20%"},
      {n:"Iceflare Bomb",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 3턴마다 공격력 +150% & 적 파괴력 −30%",te:"lancers, every 3 turns: attack +150% & enemy lethality −30%"},
      {n:"Ingenious Mastery",slot:"E",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 파괴력 +50%",te:"40% chance: lethality +50%"}],
 w:{side:"defender",stat:"Attack",name:"Steel Maze"}},
{id:"rufus",kr:"루퍼스",en:"Rufus",cls:"marksman",gen:11,rar:"leg",
 exp:[{n:"Inferno Regiment",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Armor Crush",slot:"X",k:"dmg",v:.60,tgt:"marksman",t:"궁병 매 공격 추가피해 +60% & 대상 받피 +25%",te:"marksmen, every attack: +60% extra damage & target takes +25% damage"},
      {n:"Wrathful Quake",slot:"I",v:.10,p:"20%",pe:"20% chance",t:"20% 확률 적 파괴력 −50%(2턴)",te:"20% chance: enemy lethality −50% (2 turns)"}],
 w:{side:"rally",stat:"Attack",name:"Blazing Legion"}},
// ── Gen 12~13 ──
{id:"herbjorg",kr:"헤르보르",en:"Hervor",cls:"infantry",gen:12,rar:"leg",
 exp:[{n:"Call For Blood",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"},
      {n:"Undying",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 일반 받피 −25% / 스킬 받피 −30%",te:"infantry: normal-attack damage taken −25% / skill damage taken −30%"},
      {n:"Battlethirsty",slot:"X",k:"sur",v:.15,tgt:"infantry",t:"보병 받피 −15% / 피해량 +10%",te:"infantry damage taken −15% / damage +10%"}],
 w:{side:"defender",stat:"Defense",name:"Fort of Rock"}},
{id:"karol",kr:"가로얼",en:"Karol",cls:"lancer",gen:12,rar:"leg",
 exp:[{n:"In the Wings",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Shieldbreaker",slot:"AH",v:.25,t:"적 창병에 +30% / 적 보병에 +25% 피해",te:"+30% damage vs enemy lancers / +25% vs enemy infantry"},
      {n:"Standard of Ages",slot:"B",v:.15,t:"공격력 +15% / 방어력 +10%",te:"attack +15% / defense +10%",also:{slot:"DEF",v:.10}}],
 w:{side:"rally",stat:"Attack",name:"Triumphant March"}},
{id:"ligeia",kr:"리지아",en:"Ligeia",cls:"marksman",gen:12,rar:"leg",
 exp:[{n:"Nerf Poison",slot:"F",v:.25,t:"적 전 부대 방어력 −25%",te:"all enemy troops defense −25%"},
      {n:"Corrosion",slot:"X",k:"dmg",v:.50,tgt:"marksman",t:"궁병 2격마다 추가피해 +100% & 대상 받피 +25%",te:"marksmen, every 2nd hit: +100% extra damage & target takes +25% damage"},
      {n:"Toxic Tip",slot:"X",k:"dmg",v:.50,tgt:"marksman",t:"궁병 2격마다 피해 +100% & 적 피해량 −20%",te:"marksmen, every 2nd hit: +100% damage & enemy damage −20%"}],
 w:{side:"defender",stat:"Lethality",name:"Trap Nest"}},
{id:"vulcanus",kr:"올카누스",en:"Vulcanus",cls:"marksman",gen:13,rar:"leg",
 exp:[{n:"Raging Storm",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Breaker Steel",slot:"AH",v:.20,p:"5공격마다",pe:"every 5th attack",t:"5공격마다 추가피해 +100%",te:"every 5th attack: +100% extra damage"},
      {n:"True Strike",slot:"X",k:"dmg",v:.60,tgt:"marksman",t:"적 보·창 방어력 −60% & 궁병 공격력 +60%",te:"enemy infantry & lancer defense −60% and marksman attack +60%"}],
 w:{side:"rally",stat:"Attack",name:"Born King"}},
{id:"flora",kr:"플로라",en:"Flora",cls:"lancer",gen:13,rar:"leg",
 exp:[{n:"Enmiring Vines",slot:"G",v:.25,p:"50%",pe:"50% chance",
       t:"50% 확률 적 받는 피해 +50%",te:"50% chance: enemy damage taken +50%"},
      {n:"Plantage",slot:"X",k:"dmg",v:.25,tgt:"lancer",also:{slot:"X",k:"sur",v:.25,tgt:"infantry"},
       t:"창병 협공 피해 +25% · 보병 받는 피해 −25%",te:"lancers deal +25% joint-attack damage; infantry take −25% damage"},
      {n:"Confusion Pollen",slot:"G",v:.15,p:"4턴마다 2턴",pe:"2 turns every 4 turns",
       t:"4턴마다 2턴 적 보병 받는 피해 +30% · 적 궁병 피해량 −30%",te:"every 4 turns for 2 turns: enemy infantry take +30% damage, enemy marksmen deal −30%"}],
 w:{side:"defender",stat:"Health",name:"Fruit of Life"}},
{id:"gisela",kr:"기젤라",en:"Gisela",cls:"infantry",gen:13,rar:"leg",
 exp:[{n:"Alloyed Defense",slot:"X",k:"sur",v:.30,tgt:"infantry",
       t:"보병 방어력 +30%",te:"infantry defense +30%"},
      {n:"Scavengeworks",slot:"DEF",v:.20,p:"40%",pe:"40% chance",
       t:"보병 40% 확률로 전 부대 방어력 +50% 1턴",te:"infantry: 40% chance to give all troops +50% defense for 1 turn"},
      {n:"Trial Shield",slot:"D",v:.20,p:"40%",pe:"40% chance",
       t:"40% 확률 전 부대 받는 피해 −50%",te:"40% chance: all troops damage taken −50%"}],
 w:{side:"defender",stat:"Attack",name:"Auto-Target"}},
// ── Gen 14~17 ──
{id:"cara",kr:"카라",en:"Cara",cls:"marksman",gen:14,rar:"leg",
 exp:[{n:"Smoky Encounter",slot:"I",v:.20,t:"적 전 부대 파괴력 −20%",te:"all enemy troops lethality −20%"},
      {n:"Mech Pet",slot:"An",v:.30,t:"전 부대 일반공격 피해 +30%",te:"all troops normal-attack damage +30%"},
      {n:"Witch's Wrath",slot:"X",k:"dmg",v:.20,tgt:"marksman",p:"2공격마다",pe:"every 2nd attack",
       t:"궁병 2공격마다 적 창병에 +40% · 적 궁병에 +20% 추가피해",te:"marksmen, every 2nd attack: +40% vs enemy lancers / +20% vs enemy marksmen"}],
 w:{side:"defender",stat:"Lethality",name:"Shrouded Haven"}},
{id:"dominic",kr:"도미니카",en:"Dominic",cls:"lancer",gen:14,rar:"leg",
 exp:[{n:"Mystic Mechanism",slot:"A",v:.20,t:"전 부대 피해량 +20%",te:"all troops damage +20%"},
      {n:"Spiky Assault",slot:"X",k:"dmg",v:.60,tgt:"lancer",
       t:"창병 공격당 피해 +60% · 중독 대상 받는 피해 +25%",te:"lancers: +60% damage per attack; poisoned targets take +25% damage"},
      {n:"Mirror Maze",slot:"X",k:"sur",v:.15,tgt:"inf+mar",bk:"D",also:{slot:"X",k:"dmg",v:.15,tgt:"inf+mar",bk:"A"},
       t:"보병·궁병 받는 피해 −15% · 피해량 +15%",te:"infantry & marksmen: damage taken −15%, damage dealt +15%"}],
 w:{side:"rally",stat:"Lethality",name:"Grand Fantasy"}},
{id:"elif",kr:"엘리프",en:"Elif",cls:"infantry",gen:14,rar:"leg",
 exp:[{n:"Shackling Veil",slot:"H",v:.25,t:"적 전 부대 공격력 −25%",te:"all enemy troops attack −25%"},
      {n:"Slash Formation",slot:"B",v:.15,t:"전 부대 공격력 +15% / 방어력 +10%",te:"all troops attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Enchanting Tapestry",slot:"X",k:"sur",v:.30,tgt:"infantry",
       t:"보병 공격 시 공격력 30% 실드 1턴",te:"infantry gain a shield worth 30% of attack for 1 turn"}],
 w:{side:"defender",stat:"Defense",name:"Guardian's Grace"}},
{id:"estrella",kr:"에스텔라",en:"Estrella",cls:"lancer",gen:15,rar:"leg",
 exp:[{n:"Corrosive Color",slot:"F",v:.25,t:"적 전 부대 방어력 −25%",te:"all enemy troops defense −25%"},
      {n:"Dawn Canvas",slot:"B",v:.15,t:"전 부대 공격력 +15% / 방어력 +10%",te:"all troops attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Splendid Scene",slot:"X",k:"dmg",v:.25,tgt:"lancer",bk:"A",also:{slot:"X",k:"sur",v:.25,tgt:"infantry",bk:"D"},
       t:"창병 피해량 +25% · 보병 받는 피해 −25%",te:"lancers deal +25% damage; infantry take −25% damage"}],
 w:{side:"defender",stat:"Attack",name:"Homeland Defense"}},
{id:"hank",kr:"행크",en:"Hank",cls:"infantry",gen:15,rar:"leg",
 exp:[{n:"Roaring Rage",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"},
      {n:"Flying Sparks",slot:"A",v:.10,p:"보병 5공격마다 2턴",pe:"2 turns per 5 infantry attacks",
       t:"보병 5공격마다 2턴 전 부대 피해량 +25% · 받는 피해 −25%",te:"every 5 infantry attacks: all troops damage +25% and damage taken −25% for 2 turns"},
      {n:"Raging Force",slot:"G",v:.15,p:"4턴마다 2턴",pe:"2 turns every 4 turns",
       t:"4턴마다 2턴 적 보병 받는 피해 +30% · 적 궁병 피해량 −30%",te:"every 4 turns for 2 turns: enemy infantry take +30% damage, enemy marksmen deal −30%"}],
 w:{side:"defender",stat:"Health",name:"Wall of Despair"}},
{id:"viveca",kr:"비비카",en:"Viveca",cls:"marksman",gen:15,rar:"leg",
 exp:[{n:"Nightfall Legion",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Shadow World",slot:"X",k:"dmg",v:.20,tgt:"marksman",p:"20%",pe:"20% chance",
       t:"궁병 공격 20% 확률로 추가피해 +100%",te:"marksmen: 20% chance of +100% extra damage"},
      {n:"Children of the Mist",slot:"X",k:"dmg",v:.10,tgt:"marksman",bk:"A",also:{slot:"X",k:"sur",v:.10,tgt:"infantry",bk:"D"},
       t:"궁병 피해량 +10% · 보병 받는 피해 −10%",te:"marksmen deal +10% damage; infantry take −10% damage"}],
 w:{side:"rally",stat:"Lethality",name:"Song of Dawn"}},
{id:"aisling",kr:"애슐린",en:"Aisling",cls:"marksman",gen:16,rar:"leg",
 exp:[{n:"Songs of the Ancestors",slot:"A",v:.20,t:"전 부대 피해량 +20%",te:"all troops damage +20%"},
      {n:"Rock Storm",slot:"X",k:"dmg",v:.50,tgt:"marksman",p:"3턴마다",pe:"every 3 turns",
       t:"궁병 3턴마다 추가피해 +150% · 적 피해량 −30%",te:"marksmen every 3 turns: +150% extra damage, enemy damage −30%"},
      {n:"Forest Fury",slot:"X",k:"dmg",v:.133,tgt:"marksman",p:"3턴마다",pe:"every 3 turns",
       t:"궁병 3턴마다 전 병종 상대 추가피해 +40%",te:"marksmen every 3 turns: +40% extra damage vs all troops"}],
 w:{side:"defender",stat:"Defense",name:"Forest Guardian"}},
{id:"seigel",kr:"시걸",en:"Seigel",cls:"infantry",gen:16,rar:"leg",
 exp:[{n:"Armor of Night",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"},
      {n:"Night's Defense",slot:"H",v:.35,
       t:"적 창병·궁병 공격력 −35% (내 보병 공격력 −20% 감수)",te:"enemy lancer & marksman attack −35% (own infantry attack −20%)"},
      {n:"Vanguard of Eternity",slot:"X",k:"sur",v:.30,tgt:"infantry",
       t:"보병 일반공격 받피 −25% / 스킬 받피 −30%",te:"infantry: normal-attack damage taken −25% / skill damage taken −30%"}],
 w:{side:"defender",stat:"Lethality",name:"Hell's Vow"}},
{id:"ursar",kr:"우르사",en:"Ursar",cls:"lancer",gen:16,rar:"leg",
 exp:[{n:"Forest Spores",slot:"H",v:.25,t:"적 전 부대 공격력 −25%",te:"all enemy troops attack −25%"},
      {n:"Horn of the Ancients",slot:"X",k:"dmg",v:.30,tgt:"mar+lan",
       t:"창병·궁병 파괴력 +30% 2턴 · 적 방어력 −30%",te:"lancers & marksmen lethality +30% for 2 turns; enemy defense −30%"},
      {n:"Poison Tips",slot:"X",k:"dmg",v:.50,tgt:"lancer",p:"2공격마다",pe:"every 2nd attack",
       t:"창병 2공격마다 추가피해 +100% · 대상 받는 피해 +25%",te:"lancers every 2nd attack: +100% extra damage, target takes +25% damage"}],
 w:{side:"rally",stat:"Attack",name:"Typhoon Drums"}},
{id:"aiden",kr:"에이든",en:"Aiden",cls:"infantry",gen:17,rar:"leg",
 exp:[{n:"Starfire Wall",slot:"DEF",v:.20,p:"40%",pe:"40% chance",
       t:"보병 40% 확률로 전 부대 방어력 +50% 1턴",te:"infantry: 40% chance to give all troops +50% defense for 1 turn"},
      {n:"Scarlet Brigade",slot:"B",v:.15,t:"전 부대 공격력 +15% / 방어력 +10%",te:"all troops attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Rush",slot:"B",v:.25,p:"2턴마다 1턴",pe:"1 turn every 2 turns",
       t:"2턴마다 1턴 전 부대 공격력 +50%",te:"every 2 turns: all troops attack +50% for 1 turn"}],
 w:{side:"defender",stat:"Attack",name:"Guardians of Iron"}},
{id:"bertha",kr:"버사",en:"Bertha",cls:"lancer",gen:17,rar:"leg",
 exp:[{n:"Dissection",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"},
      {n:"Vengeance",slot:"X",k:"dmg",v:.625,tgt:"lancer",also:{slot:"X",k:"dmg",v:.30,tgt:"marksman"},p:"2공격마다",pe:"every 2nd attack",
       t:"창병 2공격마다 피해 +125% · 궁병 공격력 +30% 1턴",te:"lancers every 2nd attack: +125% damage; marksmen +30% attack for 1 turn"},
      {n:"Lethal Precision",slot:"X",k:"dmg",v:.60,tgt:"lancer",
       t:"창병 공격당 추가피해 +60% · 약화 대상 받는 피해 +25%",te:"lancers: +60% bonus damage per attack; weakened targets take +25% damage"}],
 w:{side:"defender",stat:"Lethality",name:"Antibodies"}},
{id:"eleanor",kr:"엘리노어",en:"Eleanor",cls:"marksman",gen:17,rar:"leg",
 exp:[{n:"Theoretical Advantage",slot:"F",v:.25,t:"적 전 부대 방어력 −25%",te:"all enemy troops defense −25%"},
      {n:"Pierce Caliber",slot:"X",k:"dmg",v:.50,tgt:"marksman",p:"50%",pe:"50% chance",
       t:"궁병 50% 확률 추가피해 +100% · 궁병 피해량 +40% 1턴",te:"marksmen: 50% chance of +100% extra damage; marksman damage +40% for 1 turn"},
      {n:"Trajectoids",slot:"X",k:"dmg",v:.30,tgt:"marksman",p:"2공격마다",pe:"every 2 attacks",
       t:"궁병 2공격마다 적 궁병에 피해 +60%",te:"marksmen every 2 attacks: +60% damage vs enemy marksmen"}],
 w:{side:"rally",stat:"Lethality",name:"Doom Patrol"}}
];

// ── Ton 시트의 편성 행 ───────────────────────────────────────────
// EN 툴 둘("Gen 1~9" · "Gen 10+")의 편성 행을 그대로 옮겼다 (2026-09-12, CSV 수집).
//   g  = 세대 · l = 리더 [보병[], 창병[], 궁병[]] (슬래시 대안을 배열로 다 담았다)
//   rs = 라벨에 적힌 병비 **전부** ("60/40 or 60/30/10" 이면 둘 다)
//   j  = 조이너 **칸 단위** [[칸1 후보], [칸2 후보], …]
//   meta:1 = 시트 라벨이 "META - …" 로 시작하는 행 (시트가 스스로 현재 주류라고 표시한 것)
//        시트가 "Jessie*" 라고 적은 건 **한 칸**이고 그 칸의 후보가 제시/제셀/제로니모 셀이다.
//        평평하게 펌치면 제시와 제셀을 둘 다 넣어도 "시트대로"가 돼버린다 — 그러면 이 기능이
//        해결하려던 문제(같은 칸을 중복으로 잡는 것)를 그대로 놓친다.
//
// ⚠️ **시트가 한 입력에 답을 둘 적어 둔 자리가 있다.** 리더도 병비도 같은데 조이너 칸이
//    다른 행이 둘 있는 경우다(2026-09-13 CSV 재파싱에서 발견):
//      · g8  60/40/0  가토·소냐·브레들리 — 시트 Defense 행과 Offense 행에 둘 다 걸린다
//      · g12 60/20/20 헤르보르·로이드·리지아 — 둘 다 Defense 인데 답이 다르다(하나가 META)
//    **공/수 라벨로는 못 가른다** — 전무 side 는 영웅에 붙어 있어서 같은 3인조는 같은 side 다.
//    게다가 전무(위젯)는 SkillMod 칸에 안 들어가므로 공/수는 조이너 순위를 바꾸지 않는다.
//    그래서 mode 를 싣지 않는다. 대신 `matchComps()` 가 걸리는 행을 **전부** 돌려주고
//    화면이 "시트가 답을 둘 적어 뒀다"고 그대로 드러낸다. 우리가 고르지 않는다.
//
// ⚠️ **이 배열은 시트 행 순서 그대로 유지한다.** 세대·병비·META 로도 안 갈리는 동률이 남으면
//    마지막 타이브레이크가 **배열 순서**이고(안정 정렬), 화면은 그걸 "시트에 먼저 적힌 행"이라고
//    설명한다. 순서를 흐트러뜨리면 그 설명이 거짓이 된다. 실제로 g12 META 행을 복원할 때
//    쌍둥이 바로 뒤에 끼워 넣었다가 시트 순서와 어긋나서 되돌렸다(2026-09-13).
//
// 쓰는 곳은 **하나**다: 입력한 리더·병비가 이 행과 맞으면, 조이너 넷을 고를 때
// **애매한 차이는 시트 쪽으로 기울인다**(render.js 의 SHEET_EDGE).
// 배율을 바꾸는 게 아니라 거의 같은 둘 중 어느 쪽을 집느냐만 정한다.
// 맞는 행이 없으면 아무 일도 일어나지 않는다 — 그게 보통의 경우다.
const SHEET_COMPS = [
 {g:1,l:[["jeronimo"],["molly"],["zinman"]],rs:[[60,40,0],[60,10,30],[50,20,30]],j:[["lingxue"],["patrick"],["patrick"],["lumak"]]},
 {g:1,l:[["jeronimo"],["molly"],["zinman"]],rs:[[50,20,30],[30,20,50]],j:[["lingxue"],["patrick"],["patrick"],["lumak"]]},
 {g:2,l:[["flint"],["philly"],["zinman"]],rs:[[60,40,0],[60,10,30],[50,20,30]],j:[["patrick"],["jessie","jasser","jeronimo"],["seoyoon"],["sergey","bahiti","lumak"]]},
 {g:2,l:[["jeronimo"],["philly"],["alonso"]],rs:[[50,20,30],[30,20,50]],j:[["patrick"],["jessie","jasser","jeronimo"],["seoyoon"],["zinman"]]},
 {g:3,l:[["logan"],["philly"],["zinman"]],rs:[[60,40,0],[60,30,10]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["seoyoon"]]},
 {g:3,l:[["jeronimo"],["mia"],["greg"]],rs:[[50,20,30],[30,20,50]],j:[["jessie","jasser","jeronimo"],["seoyoon"],["philly"],["patrick"]]},
 {g:3,l:[["jeronimo"],["mia"],["greg","alonso"]],rs:[[60,40,0],[40,60,0]],j:[["jessie","jasser","jeronimo"],["seoyoon"],["philly"],["patrick"]]},
 {g:3,l:[["logan"],["philly"],["greg"]],rs:[[50,20,30]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["seoyoon"]]},
 {g:4,l:[["ahmose","logan"],["reina"],["lynn"]],rs:[[60,40,0],[60,30,10],[50,20,30]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["seoyoon"]]},
 {g:4,l:[["jeronimo"],["reina"],["greg"]],rs:[[50,20,30],[30,20,50]],j:[["mia"],["philly"],["patrick"],["zinman"]]},
 {g:4,l:[["jeronimo"],["mia"],["greg","alonso"]],rs:[[48,4,48],[40,10,50]],j:[["patrick"],["philly"],["zinman"],["reina"]]},
 {g:4,l:[["jeronimo"],["reina","mia"],["greg"]],rs:[[60,40,0],[40,60,0]],j:[["patrick"],["philly"],["zinman"],["mia","reina"]]},
 {g:4,l:[["ahmose","logan"],["molly","philly"],["lynn"]],rs:[[50,2,48]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["seoyoon"]]},
 {g:5,l:[["hector","logan"],["norah"],["zinman"]],rs:[[60,40,0]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["philly"]]},
 {g:5,l:[["jeronimo"],["reina"],["gwen"]],rs:[[50,20,30],[30,20,50]],j:[["mia"],["jessie","jasser","jeronimo"],["seoyoon"],["norah"]]},
 {g:5,l:[["jeronimo"],["mia"],["gwen"]],rs:[[48,4,48],[40,10,50]],j:[["norah"],["norah"],["norah"],["patrick"]]},
 {g:5,l:[["jeronimo"],["norah"],["greg"]],rs:[[60,40,0],[40,60,0]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["philly"]]},
 {g:5,l:[["logan"],["norah"],["greg"]],rs:[[60,40,0]],j:[["mia"],["norah"],["jessie","jasser","jeronimo"],["philly"]]},
 {g:6,l:[["wuming"],["norah"],["zinman"]],rs:[[60,40,0]],j:[["renee"],["mia"],["patrick"],["jessie","jasser","jeronimo"]]},
 {g:6,l:[["jeronimo"],["renee"],["gwen"]],rs:[[50,20,30],[30,20,50]],j:[["jessie","jasser","jeronimo"],["seoyoon"],["mia"],["norah"]]},
 {g:6,l:[["jeronimo","hector"],["mia"],["wayne","gwen"]],rs:[[48,4,48],[40,10,50]],j:[["norah"],["norah"],["norah"],["norah","patrick"]]},
 {g:6,l:[["jeronimo"],["renee"],["greg"]],rs:[[60,40,0],[40,60,0]],j:[["mia"],["patrick"],["jessie","jasser","jeronimo"],["wuming"]]},
 {g:6,l:[["logan"],["philly"],["wayne"]],rs:[[45,5,50],[40,0,60]],j:[["norah"],["norah"],["norah"],["norah","patrick"]],meta:1},
 {g:6,l:[["hector"],["norah"],["wayne"]],rs:[[45,15,40]],j:[["mia"],["patrick"],["philly"],["lynn"]]},
 {g:6,l:[["hector"],["molly"],["wayne"]],rs:[[50,0,50]],j:[["mia"],["patrick"],["norah"],["norah"]]},
 {g:7,l:[["edith"],["gordon"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["mia"],["reina"],["jessie","jasser","jeronimo"]]},
 {g:7,l:[["edith"],["molly","philly"],["bradley"]],rs:[[40,0,60],[48,4,48]],j:[["mia"],["norah"],["norah"],["lynn"]]},
 {g:7,l:[["jeronimo","edith"],["mia"],["bradley"]],rs:[[48,4,48],[40,10,50]],j:[["norah"],["norah"],["norah"],["patrick"]]},
 {g:8,l:[["gatot"],["sonya"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["patrick"],["mia"],["hendrik"]]},
 {g:8,l:[["gatot"],["molly","philly"],["bradley"]],rs:[[40,0,60],[48,4,48]],j:[["mia"],["patrick"],["norah"],["lynn"]]},
 {g:8,l:[["edith","jeronimo"],["mia"],["hendrik"]],rs:[[48,4,48],[40,0,60]],j:[["norah"],["norah"],["jessie","jasser","jeronimo"],["seoyoon"]]},
 {g:8,l:[["edith","gatot"],["sonya"],["bradley"]],rs:[[60,40,0],[40,60,0]],j:[["renee"],["mia"],["hendrik"],["jessie","jasser","jeronimo"]]},
 {g:8,l:[["jeronimo"],["gordon"],["bradley"]],rs:[[60,40,0],[40,60,0]],j:[["renee"],["mia"],["hendrik"],["patrick"]]},
 {g:8,l:[["jeronimo"],["mia"],["bradley"]],rs:[[48,4,48]],j:[["norah"],["norah"],["norah"],["hendrik"]]},
 {g:9,l:[["magnus"],["sonya"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["mia"],["patrick"],["hendrik"]]},
 {g:9,l:[["magnus"],["molly","philly"],["bradley","xura"]],rs:[[40,0,60],[48,4,48]],j:[["mia"],["patrick"],["norah"],["lynn"]]},
 {g:9,l:[["magnus"],["mia"],["hendrik"]],rs:[[48,4,48],[40,10,50],[40,0,60]],j:[["norah"],["norah"],["norah"],["patrick"]]},
 {g:9,l:[["magnus"],["fred"],["bradley"]],rs:[[60,40,0],[40,60,0]],j:[["renee"],["mia"],["patrick"],["hendrik"]]},
 {g:10,l:[["gregory"],["freya"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["mia"],["patrick"],["hendrik"]]},
 {g:10,l:[["gregory"],["molly","philly"],["bradley","xura"]],rs:[[40,2,58],[48,4,48]],j:[["mia"],["norah"],["hendrik"],["patrick"]]},
 {g:10,l:[["gregory"],["mia"],["blanchette"]],rs:[[48,4,48],[40,10,50]],j:[["norah"],["norah"],["hendrik"],["patrick"]]},
 {g:10,l:[["gregory"],["fred"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["mia"],["hendrik"],["patrick"]]},
 {g:11,l:[["eleonora"],["lloyd"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["mia"],["hendrik"],["reina"]]},
 {g:11,l:[["eleonora"],["molly","philly"],["xura"]],rs:[[40,2,58],[48,4,48]],j:[["mia"],["norah"],["hendrik"],["reina"]]},
 {g:11,l:[["eleonora"],["mia"],["rufus"]],rs:[[48,4,48],[40,10,50]],j:[["norah"],["norah"],["hendrik"],["gatot"]]},
 {g:11,l:[["eleonora"],["lloyd","fred"],["bradley"]],rs:[[60,40,0]],j:[["renee"],["mia"],["hendrik"],["reina"]]},
 {g:12,l:[["herbjorg"],["lloyd"],["bradley"]],rs:[[60,40,0]],j:[["mia"],["renee"],["patrick"],["hendrik"]]},
 {g:12,l:[["herbjorg"],["lloyd"],["ligeia"]],rs:[[60,20,20]],j:[["mia"],["patrick"],["norah"],["seoyoon"]]},
 {g:12,l:[["herbjorg"],["molly","philly"],["ligeia"]],rs:[[50,2,48]],j:[["mia"],["patrick"],["norah"],["gatot"]]},
 {g:12,l:[["herbjorg"],["lloyd"],["ligeia"]],rs:[[50,10,40]],j:[["mia"],["patrick"],["norah"],["gatot"]]},
 {g:12,l:[["herbjorg"],["mia"],["rufus"]],rs:[[48,4,48]],j:[["patrick"],["hendrik"],["norah"],["gatot"]]},
 {g:12,l:[["herbjorg"],["karol"],["rufus"]],rs:[[50,10,40]],j:[["mia"],["patrick"],["hendrik"],["norah"]],meta:1},
 {g:12,l:[["herbjorg"],["karol"],["bradley","greg"]],rs:[[60,40,0]],j:[["mia"],["renee"],["gatot"],["hendrik"]]},
 // 시트 Gen 12 의 **마지막 행** "META - Mix Defense - 60/20/20". 위 60/20/20 행과 리더·병비가
 // 같고 조이너만 다르다 — 2026-09-12 수집 때 중복으로 오분류해서 빠져 있었다(2026-09-13 발견).
 {g:12,l:[["herbjorg"],["lloyd"],["ligeia"]],rs:[[60,20,20]],j:[["mia"],["gatot"],["patrick"],["seoyoon"]],meta:1},
];
