// WOS 편성 계산기 — 영웅 데이터베이스
// 출처: wosheroes.com / whiteoutsurvival-community.com / whiteoutsurvival.wiki (2026-08-15 수집)
// slot 코드: A=피해량↑ An=일반공격피해↑ B=공격력↑ C=체력↑ D=받는피해↓ DEF=방어력↑
//            E=파괴력↑ F=적방어↓ G=적받는피해↑ H=적공격↓ I=적파괴력↓ J=적피해량↓
//            DODGE=회피 CRIT=치명률 X=병종한정/주기형 ECO=비전투
const HEROES = [
// ── Epic (원정스킬 2개, 전용무기 없음) ──
{id:"jessie",s:1,kr:"제시",en:"Jessie",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Stand of Arms",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"},
      {n:"Bulwarks",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"}],w:null},
{id:"jasser",s:1,kr:"재서",en:"Jasser",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Tactical Genius",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"},
      {n:"Enlightened Warfare",slot:"ECO",v:0,t:"연구 속도 +15%",te:"research speed +15%"}],w:null},
{id:"seoyoon",s:1,kr:"서윤",en:"Seo-yoon",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Rallying Beat",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Soothing Dance",slot:"ECO",v:0,t:"의무실 치료 속도 +50%",te:"infirmary healing speed +50%"}],w:null},
{id:"patrick",s:1,kr:"패트릭",en:"Patrick",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Super Nutrients",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"},
      {n:"Caloric Booster",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"}],w:null},
{id:"sergey",s:1,kr:"세르게이",en:"Sergey",cls:"infantry",gen:0,rar:"epic",
 exp:[{n:"Defenders' Edge",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Weaken",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"}],w:null},
{id:"bahiti",s:1,kr:"바히티",en:"Bahiti",cls:"marksman",gen:0,rar:"epic",
 exp:[{n:"Sixth Sense",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Fluorescence",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 피해량 +50%",te:"50% chance: damage +50%"}],w:null},
{id:"lumak",kr:"루막 보칸",en:"Lumak Bokan",cls:"lancer",gen:0,rar:"epic",
 exp:[{n:"Tactical Deception",slot:"J",v:.20,t:"적 전 부대 피해량 −20%",te:"all enemy troops damage −20%"},
      {n:"Emerald Warrior",slot:"ECO",v:0,t:"사냥 행군 속도 +100%",te:"hunting march speed +100%"}],w:null},
// ── Gen 1 ──
{id:"jeronimo",s:1,kr:"제로니모",en:"Jeronimo",cls:"infantry",gen:1,rar:"leg",
 exp:[{n:"Battle Manifesto",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"},
      {n:"Swordmentor",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Expert Swordsmanship",slot:"A",v:.15,p:"4턴중 2턴",pe:"2 turns out of 4",t:"4턴마다 2턴 피해량 +30% (시간평균 15%)",te:"2 turns out of every 4: damage +30% (time-averaged 15%)"}],
 w:{side:"rally",stat:"Attack",name:"Discernment"}},
{id:"natalia",kr:"나탈리아",en:"Natalia",cls:"infantry",gen:1,rar:"leg",
 exp:[{n:"Feral Protection",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"},
      {n:"Queen of the Wild",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Call of the Wild",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"}],
 w:{side:"rally",stat:"Lethality",name:"Invincibles"}},
{id:"molly",s:1,kr:"몰리",en:"Molly",cls:"lancer",gen:1,rar:"leg",
 exp:[{n:"Snow's Grace",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"},
      {n:"Ice Dominion",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 피해량 +50%",te:"50% chance: damage +50%"},
      {n:"Youthful Rage",slot:"A",v:.25,t:"전 부대 피해량 +25%",te:"all troops damage +25%"}],
 w:{side:"defender",stat:"Lethality",name:"Snowy Blessing"}},
{id:"zinman",s:1,kr:"진만",en:"Zinman",cls:"marksman",gen:1,rar:"leg",
 exp:[{n:"Implacable",slot:"DEF",v:.10,t:"방어력 +10% / 체력 +10%",te:"defense +10% / health +10%",also:{slot:"C",v:.10}},
      {n:"Bastionist",slot:"ECO",v:0,t:"자원 소모 −15% / 건설 속도 +15%",te:"resource cost −15% / construction speed +15%"},
      {n:"Positional Battler",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"}],
 w:{side:"defender",stat:"Attack",name:"Defend to Attack"}},
// ── Gen 2 ──
{id:"flint",kr:"플린트",en:"Flint",cls:"infantry",gen:2,rar:"leg",
 exp:[{n:"Pyromaniac",slot:"X",k:"dmg",v:1.0,tgt:"infantry",t:"보병 피해량 +100%",te:"infantry damage +100%"},
      {n:"Burning Resolve",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Immolation",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"}],
 w:{side:"defender",stat:"Attack",name:"Dragon's Breath",note:"볼트 기준(웹 미검증)"}},
{id:"philly",s:1,kr:"필리",en:"Philly",cls:"lancer",gen:2,rar:"leg",
 exp:[{n:"Vigor Tactics",slot:"B",v:.15,t:"공격력 +15% / 방어력 +10%",te:"attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Dosage Boost",slot:"A",v:.50,p:"25%",pe:"25% chance",t:"25% 확률 200% 피해",te:"25% chance: 200% damage"},
      {n:"Energizing Shot",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"}],
 w:{side:"defender",stat:"Health",name:"First Aid Training"}},
{id:"alonso",s:1,kr:"알론소",en:"Alonso",cls:"marksman",gen:2,rar:"leg",
 exp:[{n:"Onslaught",slot:"E",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 파괴력 +50%",te:"40% chance: lethality +50%"},
      {n:"Iron Strength",slot:"J",v:.10,p:"20%",pe:"20% chance",t:"20% 확률 적 피해량 −50%",te:"20% chance: enemy damage −50%"},
      {n:"Poison Harpoon",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 추가피해 +50%",te:"50% chance: +50% extra damage"}],
 w:{side:"rally",stat:"Lethality",name:"Harpoon Enhancement"}},
// ── Gen 3 ──
{id:"logan",kr:"로건",en:"Logan",cls:"infantry",gen:3,rar:"leg",
 exp:[{n:"Lion's Might",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Lion Intimidation",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Leader Inspiration",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"}],
 w:{side:"defender",stat:"Defense",name:"Strong Protection"}},
{id:"mia",s:1,kr:"미아",en:"Mia",cls:"lancer",gen:3,rar:"leg",
 exp:[{n:"Bad Luck Streak",slot:"G",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 적 받는 피해 +50%",te:"50% chance: enemy damage taken +50%"},
      {n:"Lucky Charm",slot:"A",v:.25,p:"50%",pe:"50% chance",t:"50% 확률 피해량 +50%",te:"50% chance: damage +50%"},
      {n:"Ritual Deciphering",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"}],
 w:{side:"rally",stat:"Attack",name:"Rally of Fate"}},
{id:"greg",s:1,kr:"그렉",en:"Greg",cls:"marksman",gen:3,rar:"leg",
 exp:[{n:"Sword of Justice",slot:"A",v:.08,p:"20%",pe:"20% chance",t:"20% 확률 피해량 +40%(3턴)",te:"20% chance: damage +40% (3 turns)"},
      {n:"Deterrence of Law",slot:"J",v:.10,p:"20%",pe:"20% chance",t:"20% 확률 적 피해량 −50%",te:"20% chance: enemy damage −50%"},
      {n:"Law and Order",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"}],
 w:{side:"rally",stat:"Health",name:"Trumpet of Justice"}},
// ── Gen 4 ──
{id:"ahmose",kr:"아모세",en:"Ahmose",cls:"infantry",gen:4,rar:"leg",
 exp:[{n:"Viper Formation",slot:"X",k:"sur",v:.35,tgt:"infantry",t:"4공격마다 2턴 보병 받피 −70%, 창·궁 −30%",te:"every 4th attack, 2 turns: infantry damage taken −70%, lancer/marksman −30%"},
      {n:"Prayer of Flame",slot:"X",k:"dmg",v:1.0,tgt:"infantry",t:"보병 피해량 +100%",te:"infantry damage +100%"},
      {n:"Blade of Light",slot:"X",k:"dmg",v:.60,tgt:"infantry",t:"보병 공격당 피해 +60% & 대상 받피 +25%",te:"infantry, per attack: +60% damage & target takes +25% damage"}],
 w:{side:"defender",stat:"Health",name:"Oath of Guardian"}},
{id:"reina",s:1,kr:"레이나",en:"Reina",cls:"lancer",gen:4,rar:"leg",
 exp:[{n:"Assassin's Instinct",slot:"An",v:.30,t:"일반공격 피해 +30%",te:"normal-attack damage +30%"},
      {n:"Swift Jive",slot:"DODGE",v:.20,t:"일반공격 20% 회피",te:"20% chance to dodge normal attacks"},
      {n:"Shadow Blade",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 25% 확률 200% 추가공격",te:"lancers, 25% chance: a 200% extra attack"}],
 w:{side:"rally",stat:"Lethality",name:"Fiery Invasion"}},
{id:"lynn",s:1,kr:"린",en:"Lynn",cls:"marksman",gen:4,rar:"leg",
 exp:[{n:"Song of Lion",slot:"A",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 피해량 +50%",te:"40% chance: damage +50%"},
      {n:"Melancholic Ballad",slot:"J",v:.20,t:"적 전 부대 피해량 −20%",te:"all enemy troops damage −20%"},
      {n:"Oonai Cadenza",slot:"X",k:"dmg",v:.05,tgt:"marksman",t:"궁병 3공격마다 공격력 +5% 누적",te:"marksmen, every 3rd attack: attack +5%, stacking"}],
 w:{side:"defender",stat:"Lethality",name:"Iranon's Determination"}},
// ── Gen 5 ──
{id:"hector",kr:"헥터",en:"Hector",cls:"infantry",gen:5,rar:"leg",
 exp:[{n:"Survival Instincts",slot:"D",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 받는 피해 −50%",te:"40% chance: damage taken −50%"},
      {n:"Rampant",slot:"X",k:"dmg",v:2.0,tgt:"infantry",t:"보병 피해량 +200%, 궁병 +100% (10회 감쇠)",te:"infantry damage +200%, marksmen +100% (decays over 10 procs)"},
      {n:"Blitz",slot:"A",v:.50,p:"25%",pe:"25% chance",t:"25% 확률 200% 피해",te:"25% chance: 200% damage"}],
 w:{side:"defender",stat:"Attack",name:"Goliath"}},
{id:"norah",s:1,kr:"노라",en:"Norah",cls:"lancer",gen:5,rar:"leg",
 exp:[{n:"Combined Arms",slot:"X",k:"dmg",v:.15,tgt:"inf+mar",t:"보병·궁병 받피 −15% & 피해량 +15%",te:"infantry & marksmen: damage taken −15% and damage +15%"},
      {n:"Sneak Strike",slot:"X",k:"dmg",v:.20,tgt:"lancer",t:"창병 20% 확률 추가피해 +100%",te:"lancers, 20% chance: +100% extra damage"},
      {n:"Momentum",slot:"A",v:.25,p:"창병 5공격마다",pe:"lancers, every 5th attack",t:"피해량 +25% & 받피 −25% (2턴)",te:"damage +25% & damage taken −25% (2 turns)",also:{slot:"D",v:.25}}],
 w:{side:"defender",stat:"Defense",name:"True Grit"}},
{id:"gwen",kr:"그웬",en:"Gwen",cls:"marksman",gen:5,rar:"leg",
 exp:[{n:"Eagle Vision",slot:"G",v:.25,t:"적 받는 피해 +25%",te:"enemy damage taken +25%"},
      {n:"Air Dominance",slot:"A",v:.20,p:"5공격마다",pe:"every 5th attack",t:"5공격마다 추가피해 +100%",te:"every 5th attack: +100% extra damage"},
      {n:"Blastmaster",slot:"X",k:"dmg",v:.50,tgt:"marksman",t:"궁병 4공격마다 추가피해 +50%",te:"marksmen, every 4th attack: +50% extra damage"}],
 w:{side:"rally",stat:"Lethality",name:"Marauder"}},
// ── Gen 6 ──
{id:"wuming",s:1,kr:"우밍",en:"Wu Ming",cls:"infantry",gen:6,rar:"leg",
 exp:[{n:"Shadow's Evasion",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 일반공격 받피 −25% / 스킬 받피 −30%",te:"infantry: normal-attack damage taken −25% / skill damage taken −30%"},
      {n:"Crescent Uplift",slot:"A",v:.20,t:"전 부대 피해량 +20%",te:"all troops damage +20%"},
      {n:"Elemental Resonance",slot:"A",v:.25,t:"전 부대 스킬 피해 +25%",te:"all troops skill damage +25%"}],
 w:{side:"defender",stat:"Defense",name:"Steel Discipline"}},
{id:"renee",s:1,kr:"르네",en:"Renee",cls:"lancer",gen:6,rar:"leg",
 exp:[{n:"Nightmare Trace",slot:"X",k:"dmg",v:1.0,tgt:"lancer",t:"창병 2턴마다 추가딜 200%",te:"lancers, every 2 turns: +200% extra damage"},
      {n:"Dreamcatcher",slot:"X",k:"dmg",v:1.5,tgt:"lancer",t:"표식 대상 창병 피해량 +150%",te:"vs marked targets: lancer damage +150%"},
      {n:"Dreamslice",slot:"A",v:.35,t:"표식 대상 전 부대 피해량 +75%",te:"vs marked targets: all troops damage +75%"}],
 w:{side:"rally",stat:"Lethality",name:"Wistful Enchantment"}},
{id:"wayne",kr:"웨인",en:"Wayne",cls:"marksman",gen:6,rar:"leg",
 exp:[{n:"Thunder Strike",slot:"A",v:.25,p:"4턴마다",pe:"every 4 turns",t:"4턴마다 전 부대 추가공격 100%",te:"every 4 turns: all troops deal a 100% extra attack"},
      {n:"Roundabout Hit",slot:"X",k:"dmg",v:.40,tgt:"marksman",t:"궁병 격턴 적 창병 +40%/궁병 +20% 추가피해",te:"marksmen, every other turn: +40% extra vs enemy lancers, +20% vs marksmen"},
      {n:"Fleet",slot:"CRIT",v:.25,t:"전 부대 치명률 +25%",te:"all troops crit rate +25%"}],
 w:{side:"defender",stat:"Lethality",name:"Offensive Defense"}},
// ── Gen 7 ──
{id:"edith",kr:"에디스",en:"Edith",cls:"infantry",gen:7,rar:"leg",
 exp:[{n:"Strategic Balance",slot:"X",k:"sur",v:.20,tgt:"mar+lan",t:"궁병 받피 −20% / 창병 피해량 +20%",te:"marksman damage taken −20% / lancer damage +20%"},
      {n:"Ironclad",slot:"X",k:"sur",v:.20,tgt:"infantry",t:"보병 받는 피해 −20%",te:"infantry damage taken −20%"},
      {n:"Steel Sentinel",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"}],
 w:{side:"defender",stat:"Health",name:"Fortworks"}},
{id:"gordon",kr:"고든",en:"Gordon",cls:"lancer",gen:7,rar:"leg",
 exp:[{n:"Venom Infusion",slot:"X",k:"dmg",v:.50,tgt:"lancer",t:"창병 2공격마다 추가딜 100% + 독(적 딜 −20%)",te:"lancers, every 2nd attack: +100% extra damage + poison (enemy damage −20%)"},
      {n:"Chemical Terror",slot:"X",k:"dmg",v:1.5,tgt:"lancer",t:"창병 피해량 +150% & 적 피해량 −30% (3턴마다)",te:"lancer damage +150% & enemy damage −30% (every 3 turns)"},
      {n:"Toxic Release",slot:"G",v:.30,p:"4턴마다 2턴",pe:"2 turns out of every 4",t:"적 보병 받피 +30% & 적 궁병 피해량 −30%",te:"enemy infantry damage taken +30% & enemy marksman damage −30%"}],
 w:{side:"rally",stat:"Lethality",name:"Bio Assault"}},
{id:"bradley",kr:"브래들리",en:"Bradley",cls:"marksman",gen:7,rar:"leg",
 exp:[{n:"Veteran's Might",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Power Shot",slot:"A",v:.25,t:"적 창병에 +30% / 적 보병에 +25% 피해",te:"+30% damage vs enemy lancers / +25% vs enemy infantry"},
      {n:"Tactical Assistance",slot:"A",v:.15,p:"4턴중 2턴",pe:"2 turns out of 4",t:"4턴마다 2턴 피해량 +30%",te:"2 turns out of every 4: damage +30%"}],
 w:{side:"defender",stat:"Attack",name:"Siege Insight"}},
// ── Gen 8 ──
{id:"gatot",s:1,kr:"가톳",en:"Gatot",cls:"infantry",gen:8,rar:"leg",
 exp:[{n:"Golden Guard",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 방어력 +30%",te:"infantry defense +30%"},
      {n:"King's Bestowal",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 공격 시 보호막(공격력 30%)",te:"infantry attacks grant a shield (30% of attack)"},
      {n:"Royal Legion",slot:"H",v:.25,t:"적 전 부대 공격력 −25%",te:"all enemy troops attack −25%"}],
 w:{side:"defender",stat:"Defense",name:"Indestructible City"}},
{id:"sonya",kr:"소냐",en:"Sonya",cls:"lancer",gen:8,rar:"leg",
 exp:[{n:"Treasure Hunter",slot:"A",v:.20,t:"전 부대 피해량 +20%",te:"all troops damage +20%"},
      {n:"Bounty Temptation",slot:"B",v:.25,p:"2공격마다",pe:"every 2nd attack",t:"창병 피해 +75% & 전 부대 공격력 +25%(1턴)",te:"lancer damage +75% & all troops attack +25% (1 turn)"},
      {n:"Torrential Impact",slot:"X",k:"dmg",v:2.5,tgt:"lancer",t:"창병 5턴마다 250% 피해 + 기절",te:"lancers, every 5 turns: 250% damage + stun"}],
 w:{side:"defender",stat:"Lethality",name:"Vortex Turret"}},
{id:"hendrik",s:1,kr:"헨드릭",en:"Hendrik",cls:"marksman",gen:8,rar:"leg",
 exp:[{n:"Worm's Ravage",slot:"F",v:.25,t:"적 전 부대 방어력 −25%",te:"all enemy troops defense −25%"},
      {n:"Armor of Barnacles",slot:"DEF",v:.15,p:"4턴중 2턴",pe:"2 turns out of 4",t:"4턴마다 2턴 방어력 +30%",te:"2 turns out of every 4: defense +30%"},
      {n:"Dagon's Heir",slot:"X",k:"dmg",v:.40,tgt:"marksman",t:"궁병과 3턴마다 합공 40%",te:"joint strike with marksmen every 3 turns, 40%"}],
 w:{side:"rally",stat:"Attack",name:"Abyssal Blessing"}},
// ── Gen 9 ──
{id:"magnus",kr:"마그누스",en:"Magnus",cls:"infantry",gen:9,rar:"leg",
 exp:[{n:"Rapacious",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Iron Phalanx",slot:"X",k:"sur",v:.50,tgt:"infantry",p:"40%",pe:"40% chance",t:"보병 40% 확률 방어력 +50%",te:"infantry, 40% chance: defense +50%"},
      {n:"Iceman",slot:"X",k:"sur",v:.10,tgt:"inf+mar",t:"보병 받피 −10% / 궁병 피해 +10%",te:"infantry damage taken −10% / marksman damage +10%"}],
 w:{side:"defender",stat:"Health",name:"Valoric Inspiration"}},
{id:"fred",kr:"프레드",en:"Fred",cls:"lancer",gen:9,rar:"leg",
 exp:[{n:"Hydraulic Suppression",slot:"I",v:.20,t:"적 전 부대 파괴력 −20%",te:"all enemy troops lethality −20%"},
      {n:"Acidification",slot:"G",v:.20,t:"적 보병 받는 피해 +20%",te:"enemy infantry damage taken +20%"},
      {n:"Floodbringer",slot:"X",k:"dmg",v:2.0,tgt:"lancer",t:"창병 4격마다 추가피해 +200% & 적 딜 −20%",te:"lancers, every 4th hit: +200% extra damage & enemy damage −20%"}],
 w:{side:"rally",stat:"Attack",name:"Call of the Firefighter"}},
{id:"xura",kr:"주라",en:"Xura",cls:"marksman",gen:9,rar:"leg",
 exp:[{n:"Fungal Fog",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Piercing Arrow",slot:"X",k:"dmg",v:1.0,tgt:"marksman",t:"궁병 2격마다 추가피해 +100% & 대상 받피 +25%",te:"marksmen, every 2nd hit: +100% extra damage & target takes +25% damage"},
      {n:"Unorthodoxy",slot:"X",k:"dmg",v:.15,tgt:"marksman",t:"궁병 피해량 +10% / 받피 −15%",te:"marksman damage +10% / damage taken −15%"}],
 w:{side:"defender",stat:"Attack",name:"Gaiac Hymn"}},
// ── Gen 10 ──
{id:"gregory",kr:"그레고리",en:"Gregory",cls:"infantry",gen:10,rar:"leg",
 exp:[{n:"Legion of the Sun",slot:"B",v:.15,t:"공격력 +15% / 방어력 +10%",te:"attack +15% / defense +10%",also:{slot:"DEF",v:.10}},
      {n:"Charged Assault",slot:"CRIT",v:.25,t:"전 부대 치명 확률 +25%",te:"all troops crit chance +25%"},
      {n:"Unbroken",slot:"X",k:"sur",v:.20,tgt:"infantry",t:"보병 받는 피해 −20%",te:"infantry damage taken −20%"}],
 w:{side:"defender",stat:"Lethality",name:"Day of the Guard"}},
{id:"freya",kr:"프레야",en:"Freya",cls:"lancer",gen:10,rar:"leg",
 exp:[{n:"Fog of War",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Blood Moon Scythe",slot:"X",k:"dmg",v:.50,tgt:"lancer",p:"50%",pe:"50% chance",t:"창병 50% 확률 100% 추가피해",te:"lancers, 50% chance: +100% extra damage"},
      {n:"Night's Vengeance",slot:"X",k:"dmg",v:.15,tgt:"inf+mar",t:"보병·궁병 받피 −15% & 피해량 +15%",te:"infantry & marksmen: damage taken −15% and damage +15%"}],
 w:{side:"defender",stat:"Defense",name:"Defender of the Watch"}},
{id:"blanchette",kr:"블랑쳇",en:"Blanchette",cls:"marksman",gen:10,rar:"leg",
 exp:[{n:"Armed to the Teeth",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"},
      {n:"Blood Hunter",slot:"X",k:"dmg",v:.75,tgt:"marksman",t:"궁병 3라운드마다 추가피해 +75%",te:"marksmen, every 3rd round: +75% extra damage"},
      {n:"Crimson Sniper",slot:"X",k:"dmg",v:.40,tgt:"marksman",t:"궁병 2격마다 적 창병 +40%/궁병 +20%",te:"marksmen, every 2nd hit: +40% vs enemy lancers, +20% vs marksmen"}],
 w:{side:"rally",stat:"Lethality",name:"Lightning Strike"}},
// ── Gen 11 ──
{id:"eleonora",kr:"엘레오노라",en:"Eleonora",cls:"infantry",gen:11,rar:"leg",
 exp:[{n:"Scorching Sun",slot:"C",v:.25,t:"전 부대 체력 +25%",te:"all troops health +25%"},
      {n:"Solaris Nexus",slot:"X",k:"sur",v:.10,tgt:"inf+mar",t:"보병 받피 −10% / 궁병 피해량 +10%",te:"infantry damage taken −10% / marksman damage +10%"},
      {n:"Soaring Flame",slot:"A",v:.25,p:"보병 5공격마다",pe:"infantry, every 5th attack",t:"피해량 +25% & 받피 −25% (2턴)",te:"damage +25% & damage taken −25% (2 turns)",also:{slot:"D",v:.25}}],
 w:{side:"defender",stat:"Health",name:"Last Fortress"}},
{id:"lloyd",kr:"로이드",en:"Lloyd",cls:"lancer",gen:11,rar:"leg",
 exp:[{n:"Bird Invasion",slot:"I",v:.20,t:"적 전 부대 파괴력 −20%",te:"all enemy troops lethality −20%"},
      {n:"Iceflare Bomb",slot:"X",k:"dmg",v:1.5,tgt:"lancer",t:"창병 3턴마다 공격력 +150% & 적 파괴력 −30%",te:"lancers, every 3 turns: attack +150% & enemy lethality −30%"},
      {n:"Ingenious Mastery",slot:"E",v:.20,p:"40%",pe:"40% chance",t:"40% 확률 파괴력 +50%",te:"40% chance: lethality +50%"}],
 w:{side:"defender",stat:"Attack",name:"Steel Maze"}},
{id:"rufus",kr:"루퍼스",en:"Rufus",cls:"marksman",gen:11,rar:"leg",
 exp:[{n:"Inferno Regiment",slot:"B",v:.25,t:"전 부대 공격력 +25%",te:"all troops attack +25%"},
      {n:"Armor Crush",slot:"X",k:"dmg",v:.60,tgt:"marksman",t:"궁병 매 공격 추가피해 +60% & 대상 받피 +25%",te:"marksmen, every attack: +60% extra damage & target takes +25% damage"},
      {n:"Wrathful Quake",slot:"I",v:.10,p:"20%",pe:"20% chance",t:"20% 확률 적 파괴력 −50%(2턴)",te:"20% chance: enemy lethality −50% (2 turns)"}],
 w:{side:"rally",stat:"Attack",name:"Blazing Legion"}},
// ── Gen 12~13 ──
{id:"herbjorg",kr:"헤르보르",en:"Hervor",cls:"infantry",gen:12,rar:"leg",
 exp:[{n:"Call For Blood",slot:"E",v:.25,t:"전 부대 파괴력 +25%",te:"all troops lethality +25%"},
      {n:"Undying",slot:"X",k:"sur",v:.30,tgt:"infantry",t:"보병 일반 받피 −25% / 스킬 받피 −30%",te:"infantry: normal-attack damage taken −25% / skill damage taken −30%"},
      {n:"Battlethirsty",slot:"X",k:"sur",v:.15,tgt:"infantry",t:"보병 받피 −15% / 피해량 +10%",te:"infantry damage taken −15% / damage +10%"}],
 w:{side:"defender",stat:"Defense",name:"Fort of Rock"}},
{id:"karol",kr:"카롤",en:"Karol",cls:"lancer",gen:12,rar:"leg",
 exp:[{n:"In the Wings",slot:"D",v:.20,t:"전 부대 받는 피해 −20%",te:"all troops damage taken −20%"},
      {n:"Shieldbreaker",slot:"A",v:.25,t:"적 창병에 +30% / 적 보병에 +25% 피해",te:"+30% damage vs enemy lancers / +25% vs enemy infantry"},
      {n:"Standard of Ages",slot:"B",v:.15,t:"공격력 +15% / 방어력 +10%",te:"attack +15% / defense +10%",also:{slot:"DEF",v:.10}}],
 w:{side:"rally",stat:"Attack",name:"Triumphant March"}},
{id:"ligeia",kr:"리게이아",en:"Ligeia",cls:"marksman",gen:12,rar:"leg",
 exp:[{n:"Nerf Poison",slot:"F",v:.25,t:"적 전 부대 방어력 −25%",te:"all enemy troops defense −25%"},
      {n:"Corrosion",slot:"X",k:"dmg",v:1.0,tgt:"marksman",t:"궁병 2격마다 추가피해 +100% & 대상 받피 +25%",te:"marksmen, every 2nd hit: +100% extra damage & target takes +25% damage"},
      {n:"Toxic Tip",slot:"X",k:"dmg",v:1.0,tgt:"marksman",t:"궁병 2격마다 피해 +100% & 적 피해량 −20%",te:"marksmen, every 2nd hit: +100% damage & enemy damage −20%"}],
 w:{side:"defender",stat:"Lethality",name:"Trap Nest"}},
{id:"vulcanus",kr:"불카누스",en:"Vulcanus",cls:"marksman",gen:13,rar:"leg",
 exp:[{n:"Raging Storm",slot:"H",v:.20,t:"적 전 부대 공격력 −20%",te:"all enemy troops attack −20%"},
      {n:"Breaker Steel",slot:"A",v:.20,p:"5공격마다",pe:"every 5th attack",t:"5공격마다 추가피해 +100%",te:"every 5th attack: +100% extra damage"},
      {n:"True Strike",slot:"X",k:"dmg",v:.60,tgt:"marksman",t:"적 보·창 방어력 −60% & 궁병 공격력 +60%",te:"enemy infantry & lancer defense −60% and marksman attack +60%"}],
 w:{side:"rally",stat:"Attack",name:"Born King"}}
];
